spring.application.name=receitas-api

spring.datasource.url=jdbc:postgresql://localhost:5433/receitasdb
spring.datasource.username=receitas
spring.datasource.password=receitas123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true